%global selinuxtype targeted
%global selinuxmodulename insights_ansible_playbook_verifier

Name:     insights-ansible-playbook-verifier
Version:  0.1.0
Release:  0%{dist}
Summary:  Ansible playbook verifier for Red Hat Insights
License:  MIT

URL:      https://github.com/RedHatInsights/%{name}
# Source0:  %{url}/archive/refs/tags/v%{version}.tar.gz
Source0:  %{name}-%{version}.tar.gz

BuildArch: noarch

BuildRequires: python3-devel
BuildRequires: selinux-policy-devel
Requires: gpg
Requires: (%{name}-selinux = %{version}-%{release} if selinux-policy-%{selinuxtype})
%generate_buildrequires
%pyproject_buildrequires

%description
insights-ansible-playbook-verifier package cryptographically verifies Ansible
playbooks generated by Red Hat Insights.

%package selinux
Requires: selinux-policy-%{selinuxtype}
Requires(post): selinux-policy-%{selinuxtype}
%{?selinux_requires}

Summary: SELinux policies for %{name}

%description selinux
Custom SELinux policy module for %{name}.

%prep
%autosetup -p1

%build
%pyproject_wheel

%install
%pyproject_install insights_ansible_playbook_lib insights_ansible_playbook_verifier
mkdir -p %{buildroot}/%{_libexecdir}
mv %{buildroot}%{_bindir}/%{name} %{buildroot}%{_libexecdir}
mkdir -p %{buildroot}/%{_localstatedir}/lib/%{name}/
%pyproject_save_files insights_ansible_playbook_lib insights_ansible_playbook_verifier

mkdir -p %{buildroot}%{_localstatedir}/lib/%{name}

%make_install PREFIX=%{_prefix} DATADIR=%{_datadir} SELINUXTYPE=%{selinuxtype}

%check
%pyproject_check_import insights_ansible_playbook_lib insights_ansible_playbook_verifier

%files -n %{name} -f %{pyproject_files}
%{_libexecdir}/%{name}
%attr(700,root,root) %dir %{_localstatedir}/lib/%{name}/
%license LICENSE

%files selinux
%{_datadir}/selinux/packages/%{selinuxtype}/%{selinuxmodulename}.pp.*
%{_datadir}/selinux/devel/include/distributed/%{selinuxmodulename}.if
%ghost %verify(not md5 size mode mtime) %{_sharedstatedir}/selinux/%{selinuxtype}/active/modules/200/%{selinuxmodulename}
%license LICENSE

%pre selinux
%selinux_relabel_pre -s %{selinuxtype}

%post selinux
%selinux_modules_install -s %{selinuxtype} %{_datadir}/selinux/packages/%{selinuxtype}/%{selinuxmodulename}.pp.bz2

%postun selinux
if [ $1 -eq 0 ]; then
    %selinux_modules_uninstall -s %{selinuxtype} %{selinuxmodulename}
fi

%posttrans selinux
%selinux_relabel_post -s %{selinuxtype}

%changelog
%autochangelog
